### ISSUE TITLE
ANR Exception

### ISSUE THREAD

**Issue by android9527** [ChartBoost/chartboost-mediation-android-sdk-demo#12]
I go ANR when loading Ad with facebook bidding.
the method **com.facebook.ads.BidderTokenProvider.getBidderToken()** should be call on the work thread.

LG Nexus 5 Android 6.0.1

Helium SDK v2.3.2
helium-facebook:2.3.2.0
Facebook SDK v6.8.0

Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys'
ABI: 'arm'
Build type: optimized
Zygote loaded classes=3978 post zygote classes=3889
Intern table: 50641 strong; 228 weak
JNI: CheckJNI is on; globals=507 (plus 428 weak)
Libraries: /data/app/com.google.android.webview-2/lib/arm/libwebviewchromium.so /system/lib/libandroid.so /system/lib/libcompiler_rt.so /system/lib/libjavacrypto.so /system/lib/libjnigraphics.so /system/lib/libmedia_jni.so /system/lib/libwebviewchromium_loader.so /system/lib/libwebviewchromium_plat_support.so libjavacore.so (9)
Heap: 19% free, 27MB/34MB; 125681 objects
Dumping cumulative Gc timings
Start Dumping histograms for 1 iterations for partial concurrent mark sweep
MarkRootsCheckpoint:	Sum: 76.218ms 99% C.I. 3.529ms-72.112ms Avg: 38.109ms Max: 72.689ms
ProcessMarkStack:	Sum: 9.434ms 99% C.I. 0.016ms-9.165ms Avg: 3.144ms Max: 9.207ms
SweepMallocSpace:	Sum: 7.582ms 99% C.I. 0.024ms-7.525ms Avg: 3.791ms Max: 7.558ms
UpdateAndMarkZygoteModUnionTable:	Sum: 4.476ms 99% C.I. 4.476ms-4.476ms Avg: 4.476ms Max: 4.476ms
MarkConcurrentRoots:	Sum: 2.679ms 99% C.I. 0.102ms-2.575ms Avg: 1.339ms Max: 2.577ms
SweepLargeObjects:	Sum: 2.592ms 99% C.I. 2.592ms-2.592ms Avg: 2.592ms Max: 2.592ms
UpdateAndMarkImageModUnionTable:	Sum: 2.436ms 99% C.I. 2.436ms-2.436ms Avg: 2.436ms Max: 2.436ms
ScanGrayAllocSpaceObjects:	Sum: 1.450ms 99% C.I. 5us-1436us Avg: 725us Max: 1445us
MarkAllocStackAsLive:	Sum: 1.128ms 99% C.I. 1.128ms-1.128ms Avg: 1.128ms Max: 1.128ms
ReMarkRoots:	Sum: 627us 99% C.I. 627us-627us Avg: 627us Max: 627us
(Paused)ScanGrayAllocSpaceObjects:	Sum: 249us 99% C.I. 1us-248us Avg: 124.500us Max: 248us
AllocSpaceClearCards:	Sum: 184us 99% C.I. 1us-130us Avg: 46us Max: 130us
ImageModUnionClearCards:	Sum: 161us 99% C.I. 63us-98us Avg: 80.500us Max: 98us
EnqueueFinalizerReferences:	Sum: 149us 99% C.I. 149us-149us Avg: 149us Max: 149us
FinishPhase:	Sum: 143us 99% C.I. 143us-143us Avg: 143us Max: 143us
ScanGrayImageSpaceObjects:	Sum: 117us 99% C.I. 117us-117us Avg: 117us Max: 117us
MarkNonThreadRoots:	Sum: 96us 99% C.I. 28us-68us Avg: 48us Max: 68us
SweepSystemWeaks:	Sum: 75us 99% C.I. 75us-75us Avg: 75us Max: 75us
(Paused)ScanGrayImageSpaceObjects:	Sum: 56us 99% C.I. 56us-56us Avg: 56us Max: 56us
RevokeAllThreadLocalAllocationStacks:	Sum: 38us 99% C.I. 38us-38us Avg: 38us Max: 38us
ZygoteModUnionClearCards:	Sum: 28us 99% C.I. 14us-14us Avg: 14us Max: 14us
ProcessReferences:	Sum: 23us 99% C.I. 23us-23us Avg: 23us Max: 23us
MarkingPhase:	Sum: 20us 99% C.I. 20us-20us Avg: 20us Max: 20us
(Paused)PausePhase:	Sum: 17us 99% C.I. 17us-17us Avg: 17us Max: 17us
ScanGrayZygoteSpaceObjects:	Sum: 15us 99% C.I. 15us-15us Avg: 15us Max: 15us
Sweep:	Sum: 14us 99% C.I. 14us-14us Avg: 14us Max: 14us
ProcessCards:	Sum: 13us 99% C.I. 6us-7us Avg: 6.500us Max: 7us
ReclaimPhase:	Sum: 12us 99% C.I. 12us-12us Avg: 12us Max: 12us
(Paused)ScanGrayZygoteSpaceObjects:	Sum: 11us 99% C.I. 11us-11us Avg: 11us Max: 11us
MarkRoots:	Sum: 6us 99% C.I. 6us-6us Avg: 6us Max: 6us
(Paused)ProcessMarkStack:	Sum: 3us 99% C.I. 3us-3us Avg: 3us Max: 3us
BindBitmaps:	Sum: 2us 99% C.I. 2us-2us Avg: 2us Max: 2us
FindDefaultSpaceBitmap:	Sum: 1us 99% C.I. 1us-1us Avg: 1us Max: 1us
PreSweepingGcVerification:	Sum: 0 99% C.I. 0ns-0ns Avg: 0ns Max: 0ns
Done Dumping histograms 
partial concurrent mark sweep paused:	Sum: 3.282ms 99% C.I. 3.282ms-3.282ms Avg: 3.282ms Max: 3.282ms
partial concurrent mark sweep total time: 110.094ms mean time: 110.094ms
partial concurrent mark sweep freed: 41852 objects with total size 4MB
partial concurrent mark sweep throughput: 380473/s / 42MB/s
Start Dumping histograms for 3 iterations for sticky concurrent mark sweep
MarkRootsCheckpoint:	Sum: 146.877ms 99% C.I. 6.920ms-38.547ms Avg: 24.479ms Max: 38.547ms
FreeList:	Sum: 48.449ms 99% C.I. 17us-444.750us Avg: 184.216us Max: 651us
ScanGrayAllocSpaceObjects:	Sum: 37.772ms 99% C.I. 0.004ms-23.064ms Avg: 3.147ms Max: 23.778ms
SweepArray:	Sum: 16.032ms 99% C.I. 2.276ms-7.827ms Avg: 5.344ms Max: 7.827ms
ReMarkRoots:	Sum: 16.007ms 99% C.I. 1.943ms-9.426ms Avg: 5.335ms Max: 9.468ms
ProcessMarkStack:	Sum: 11.032ms 99% C.I. 1us-5098us Avg: 919.333us Max: 5127us
MarkConcurrentRoots:	Sum: 9.415ms 99% C.I. 0.011ms-3.204ms Avg: 1.569ms Max: 3.204ms
ScanGrayImageSpaceObjects:	Sum: 7.239ms 99% C.I. 0.060ms-3.259ms Avg: 1.206ms Max: 3.259ms
AllocSpaceClearCards:	Sum: 4.356ms 99% C.I. 1us-1555us Avg: 363us Max: 1597us
SweepSystemWeaks:	Sum: 3.045ms 99% C.I. 0.121ms-2.754ms Avg: 1.015ms Max: 2.754ms
(Paused)ScanGrayAllocSpaceObjects:	Sum: 2.478ms 99% C.I. 1us-1567us Avg: 413us Max: 1585us
MarkingPhase:	Sum: 1.050ms 99% C.I. 236us-558us Avg: 350us Max: 558us
EnqueueFinalizerReferences:	Sum: 945us 99% C.I. 8us-552us Avg: 315us Max: 552us
ResetStack:	Sum: 568us 99% C.I. 146us-214us Avg: 189.333us Max: 214us
ScanGrayZygoteSpaceObjects:	Sum: 556us 99% C.I. 11us-438us Avg: 92.666us Max: 438us
ImageModUnionClearCards:	Sum: 492us 99% C.I. 53us-124us Avg: 82us Max: 124us
RevokeAllThreadLocalAllocationStacks:	Sum: 327us 99% C.I. 18us-232us Avg: 109us Max: 232us
MarkNonThreadRoots:	Sum: 242us 99% C.I. 21us-53us Avg: 40.333us Max: 53us
FinishPhase:	Sum: 224us 99% C.I. 51us-116us Avg: 74.666us Max: 116us
(Paused)ScanGrayImageSpaceObjects:	Sum: 184us 99% C.I. 57us-69us Avg: 61.333us Max: 69us
ZygoteModUnionClearCards:	Sum: 120us 99% C.I. 13us-46us Avg: 20us Max: 46us
(Paused)PausePhase:	Sum: 95us 99% C.I. 18us-55us Avg: 31.666us Max: 55us
ReclaimPhase:	Sum: 80us 99% C.I. 13us-53us Avg: 26.666us Max: 53us
PreCleanCards:	Sum: 54us 99% C.I. 17us-19us Avg: 18us Max: 19us
ProcessReferences:	Sum: 49us 99% C.I. 8us-22us Avg: 16.333us Max: 22us
ProcessCards:	Sum: 45us 99% C.I. 7us-9us Avg: 7.500us Max: 9us
(Paused)ScanGrayZygoteSpaceObjects:	Sum: 37us 99% C.I. 11us-14us Avg: 12.333us Max: 14us
SwapBitmaps:	Sum: 24us 99% C.I. 6us-9us Avg: 8us Max: 9us
InitializePhase:	Sum: 23us 99% C.I. 1us-21us Avg: 7.666us Max: 21us
MarkRoots:	Sum: 19us 99% C.I. 6us-7us Avg: 6.333us Max: 7us
(Paused)ProcessMarkStack:	Sum: 16us 99% C.I. 1us-13us Avg: 5.333us Max: 13us
ForwardSoftReferences:	Sum: 9us 99% C.I. 2us-4us Avg: 3us Max: 4us
BindBitmaps:	Sum: 8us 99% C.I. 2us-4us Avg: 2.666us Max: 4us
RecordFree:	Sum: 7us 99% C.I. 2us-3us Avg: 2.333us Max: 3us
FindDefaultSpaceBitmap:	Sum: 3us 99% C.I. 1us-1us Avg: 1us Max: 1us
PreSweepingGcVerification:	Sum: 1us 99% C.I. 250ns-1000ns Avg: 333ns Max: 1000ns
Done Dumping histograms 
sticky concurrent mark sweep paused:	Sum: 22.755ms 99% C.I. 2.699ms-13.402ms Avg: 7.585ms Max: 13.442ms
sticky concurrent mark sweep total time: 307.904ms mean time: 102.634ms
sticky concurrent mark sweep freed: 264672 objects with total size 20MB
sticky concurrent mark sweep throughput: 862124/s / 67MB/s
Total time spent in GC: 417.998ms
Mean GC size throughput: 53MB/s
Mean GC object throughput: 733023 objects/s
Total number of allocations 432083
Total bytes allocated 50MB
Total bytes freed 22MB
Free memory 6MB
Free memory until GC 6MB
Free memory until OOME 164MB
Total memory 34MB
Max memory 192MB
Zygote space size 1316KB
Total mutator paused time: 26.037ms
Total time waiting for GC to complete: 14.115us
Total GC count: 4
Total GC time: 417.998ms
Total blocking GC count: 0
Total blocking GC time: 0
Histogram of GC count per 10000 ms: 0:1,3:1
Histogram of blocking GC count per 10000 ms: 0:2

suspend all histogram:	Sum: 6.588ms 99% C.I. 3us-3277.760us Avg: 313.714us Max: 3355us
DALVIK THREADS (122):
"Signal Catcher" daemon prio=5 tid=2 Runnable
  | group="system" sCount=0 dsCount=0 obj=0x12d960a0 self=0xaee90000
  | sysTid=4020 nice=0 cgrp=default sched=0/0 handle=0xb44ee930
  | state=R schedstat=( 11579062 4428180 8 ) utm=1 stm=0 core=1 HZ=100
  | stack=0xb43f2000-0xb43f4000 stackSize=1014KB
  | held mutexes= "mutator lock"(shared held)
  native: #00 pc 00370e01  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+160)
  native: #01 pc 0035046f  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+150)
  native: #02 pc 0035a373  /system/lib/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+442)
  native: #03 pc 0035af31  /system/lib/libart.so (_ZN3art10ThreadList13RunCheckpointEPNS_7ClosureE+212)
  native: #04 pc 0035b45f  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+142)
  native: #05 pc 0035bb6f  /system/lib/libart.so (_ZN3art10ThreadList14DumpForSigQuitERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+334)
  native: #06 pc 00333cb7  /system/lib/libart.so (_ZN3art7Runtime14DumpForSigQuitERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+74)
  native: #07 pc 0033b01d  /system/lib/libart.so (_ZN3art13SignalCatcher13HandleSigQuitEv+928)
  native: #08 pc 0033b901  /system/lib/libart.so (_ZN3art13SignalCatcher3RunEPv+340)
  native: #09 pc 0003f45f  /system/lib/libc.so (_ZL15__pthread_startPv+30)
  native: #10 pc 00019b43  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)

"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x733932a0 self=0xb4df6500
  | sysTid=4014 nice=-4 cgrp=default sched=0/0 handle=0xb6ff3b34
  | state=S schedstat=( 1133809190 275895335 2073 ) utm=77 stm=36 core=2 HZ=100
  | stack=0xbe1bb000-0xbe1bd000 stackSize=8MB
  | held mutexes=
  at com.facebook.ads.redexgen.X.67.A06(:-1)
  - waiting to lock <0x0df0bd49> (a com.facebook.ads.redexgen.X.67) held by thread 57
  at com.facebook.ads.redexgen.X.5F.getBidderToken(:13670)
  at com.facebook.ads.BidderTokenProvider.getBidderToken(BidderTokenProvider.java:28)
  at com.chartboost.heliumsdk.facebookadapter.FacebookAdapter.getBidderConstants(FacebookAdapter.java:232)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.chartboost.heliumsdk.proxies.BasePartnerProxy$a.onAdapterInit(SourceFile:6)
  at com.chartboost.heliumsdk.facebookadapter.FacebookAdapter$3.onInitialized(FacebookAdapter.java:138)
  at com.facebook.ads.redexgen.X.XZ.A06(:66596)
  at com.facebook.ads.redexgen.X.L7.run(:42790)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by helenhdez04-cloud** [comment]
#``
